version: "3.5"

services:

  nginx:
    build:
      context: ./nginx
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-localhost}
    ports:
      - ${BH_PORT:-25060}:${NGINX_PORT:-80}
    volumes:
      - ./nginx/ssl:/ssl
      - ./nginx/var_www_html:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - api
      - strapi
      - bhadminer

  strapi:
    build:
      context: ./strapi
      target: dev
    environment:
      - STRAPI_DATABASE_HOST=${DB_HOST:-db}
      - STRAPI_DATABASE_PORT=${DB_PORT:-3306}
      - STRAPI_DATABASE_NAME=${DB_NAME:-bighit}
      - STRAPI_DATABASE_USER=${DB_USER:-admin}
      - STRAPI_DATABASE_PASSWORD=${DB_PASS:-dbpass}
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/home/node/app
    restart: unless-stopped
    depends_on:
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:8081
    environment:
      - API_DATABASE_HOST=${DB_HOST:-db}
      - API_DATABASE_PORT=${DB_PORT:-3306}
      - API_DATABASE_NAME=${DB_NAME:-bighit}
      - API_DATABASE_USER=${DB_USER:-admin}
      - API_DATABASE_PASSWORD=${DB_PASS:-dbpass}
    volumes:
      - pnpm:/home/node/.pnpm-store
      - ./api:/home/node/app
    restart: unless-stopped
    depends_on:
      - strapi
      - db

  db:
    image: mariadb:10.6
    volumes:
      - mariadata:/var/lib/mysql
      - ./db/data:/docker0entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="12345"
      - MYSQL_DATABASE=${DB_NAME:-bighit}
      - MYSQL_USER=${DB_USER:-admin}
      - MYSQL_PASSWORD=${DB_PASSWORD:-dbpass}
      - APP_ENV=local

  bhadminer:
    image: adminer
    restart: always

volumes:
  mariadata:
  pnpm:
    external: true
